server:
  port: 8081

spring:
  application:
    name: product-server

# nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


security:
  oauth2:
    resource:
      jwt:
        key-value: jwt_sign_key