# nacos
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


#  redis:
#    host: localhost
#    port: 6379
#    password: 123456

logging:
  level:
    org:
      springframework:
        security: DEBUG

